development:
  host: localhost
  database: weightloss_development

test:
  host: localhost
  database: weightloss_test

# set these environment variables on your prod server
production:
  host: localhost
  # port: 33187
  # username: weight_loss
  # password: password
  database: weightloss_production
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
